#!/bin/bash

function help {
    echo "[ERROR] You need to provide the URL to download the EVE Online Types images."
    echo "[ERROR] Example: http://content.eveonline.com/data/SOME_EXPANSION_Types.zip"
    echo "[ERROR] The URL can be found here: https://developers.eveonline.com/resource/resources"
    echo ""
    echo "Supported extension for archive: zip, tar, bz2, gz (bz2 and gz are considered as tar.gz and tar.bz2)"
    echo "The result folder must be called 'Types'"
    echo ""
    echo "Syntaxe: $0 <EVE Types URL>"
}

if [[ $# -lt 1 ]]
then
    help
    exit 1
fi

URL=$1

# create the tmp folder, force empty it
echo "[INFO] Downloading $URL"
mkdir -p /tmp/eve_types
rm -f /tmp/eve_types/*
wget $URL -P /tmp/eve_types

filename=$(ls /tmp/eve_types)
extension="${filename##*.}"

echo "[INFO] unzipping file..."
case $extension in
    'zip') unzip -q /tmp/eve_types/${filename} -d /tmp/eve_types ;;
    'gz') tar xzf /tmp/eve_types/${filename} -C /tmp/eve_types ;;
    'tar') tar xf /tmp/eve_types/${filename} -C /tmp/eve_types ;;
    'bz2') tar xjf /tmp/eve_types/${filename} -C /tmp/eve_types ;;
    *) help; exit 2;;
esac

# copy files in /static, link from lb/static (to save space).
echo "[INFO] Copy Types folder in static files"
rm -fR /static/ccp/Types
cp -fR /tmp/eve_types/Types /static/ccp/
ln -sf /static/ccp/Types /lb/lazyblacksmith/static/ccp/

# clean tmp files
rm -fR /tmp/eve_types

echo "[INFO] Eve Types images downloaded."
exit 0