"""Add task state table, remove task status

Revision ID: 1ab760813798
Revises: f637f29c715c
Create Date: 2017-02-03 13:25:45.348408

"""

# revision identifiers, used by Alembic.
revision = '1ab760813798'
down_revision = 'f637f29c715c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_state',
    sa.Column('task_id', sa.String(length=250), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_table('task_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('expire', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_run', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    )
    op.drop_table('task_state')
    # ### end Alembic commands ###
