"""add user pref

Revision ID: 1d7cccca46b3
Revises: 3948980c7a13
Create Date: 2017-01-16 12:25:35.209790

"""

# revision identifiers, used by Alembic.
revision = '1d7cccca46b3'
down_revision = '3948980c7a13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('invention_facility', sa.Integer(), nullable=False),
    sa.Column('invention_invention_rig', sa.Integer(), nullable=False),
    sa.Column('invention_copy_rig', sa.Integer(), nullable=False),
    sa.Column('invention_security', sa.String(length=1), nullable=False),
    sa.Column('invention_system', sa.String(length=100), nullable=False),
    sa.Column('invention_price_region', sa.Integer(), nullable=False),
    sa.Column('invention_price_type', sa.String(length=4), nullable=False),
    sa.Column('research_facility', sa.Integer(), nullable=False),
    sa.Column('research_me_rig', sa.Integer(), nullable=False),
    sa.Column('research_te_rig', sa.Integer(), nullable=False),
    sa.Column('research_copy_rig', sa.Integer(), nullable=False),
    sa.Column('research_security', sa.String(length=1), nullable=False),
    sa.Column('research_system', sa.String(length=100), nullable=False),
    sa.Column('prod_facility', sa.Integer(), nullable=False),
    sa.Column('prod_me_rig', sa.Integer(), nullable=False),
    sa.Column('prod_te_rig', sa.Integer(), nullable=False),
    sa.Column('prod_security', sa.String(length=1), nullable=False),
    sa.Column('prod_system', sa.String(length=100), nullable=False),
    sa.Column('prod_sub_facility', sa.Integer(), nullable=False),
    sa.Column('prod_sub_me_rig', sa.Integer(), nullable=False),
    sa.Column('prod_sub_te_rig', sa.Integer(), nullable=False),
    sa.Column('prod_sub_security', sa.String(length=1), nullable=False),
    sa.Column('prod_sub_system', sa.String(length=100), nullable=False),
    sa.Column('prod_price_region_minerals', sa.Integer(), nullable=False),
    sa.Column('prod_price_region_pi', sa.Integer(), nullable=False),
    sa.Column('prod_price_region_moongoo', sa.Integer(), nullable=False),
    sa.Column('prod_price_region_others', sa.Integer(), nullable=False),
    sa.Column('prod_price_type_minerals', sa.String(length=4), nullable=False),
    sa.Column('prod_price_type_pi', sa.String(length=4), nullable=False),
    sa.Column('prod_price_type_moongoo', sa.String(length=4), nullable=False),
    sa.Column('prod_price_type_others', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.character_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    # ### end Alembic commands ###
