"""add admin flag to user

Revision ID: 1e2c15118d41
Revises: ef98dde149ee
Create Date: 2017-01-08 21:44:05.195000

"""

# revision identifiers, used by Alembic.
revision = '1e2c15118d41'
down_revision = 'ef98dde149ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eve_user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eve_user', 'is_admin')
    # ### end Alembic commands ###
