"""sde tables

Revision ID: 1e3725cda0b7
Revises: None
Create Date: 2015-05-25 18:35:38.132000

"""

# revision identifiers, used by Alembic.
revision = '1e3725cda0b7'
down_revision = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('max_production_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('activity', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'activity')
    )
    op.create_table('activity_material',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'activity', 'material_id')
    )
    op.create_table('activity_product',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Numeric(precision=3, scale=2, decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'activity', 'product_id')
    )
    op.create_table('activity_skill',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'activity', 'skill_id')
    )
    op.create_table('constellation',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solar_system',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellation.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.drop_table('solar_system')
    op.drop_table('constellation')
    op.drop_table('activity_skill')
    op.drop_table('activity_product')
    op.drop_table('activity_material')
    op.drop_table('activity')
    op.drop_table('region')
    op.drop_table('item')
    ### end Alembic commands ###
