"""remove_update_at_field

Revision ID: 1eb336920751
Revises: 88d46e8e73ef
Create Date: 2016-08-04 11:07:42.214227

"""

# revision identifiers, used by Alembic.
revision = '1eb336920751'
down_revision = '88d46e8e73ef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_adjusted_price', 'update_at')
    op.drop_column('item_price', 'update_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_price', sa.Column('update_at', mysql.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('item_adjusted_price', sa.Column('update_at', mysql.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    ### end Alembic commands ###
