"""Add OreRefining table

Revision ID: 479a4b40f818
Revises: a708fc036755
Create Date: 2016-08-18 11:09:34.794750

"""

# revision identifiers, used by Alembic.
revision = '479a4b40f818'
down_revision = 'a708fc036755'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ore_refining',
    sa.Column('ore_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['ore_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('ore_id', 'material_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ore_refining')
    ### end Alembic commands ###
