"""industry_index

Revision ID: 53eb8abce4de
Revises: 1e3725cda0b7
Create Date: 2015-06-19 10:38:31.398000

"""

# revision identifiers, used by Alembic.
revision = '53eb8abce4de'
down_revision = '1e3725cda0b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_index',
    sa.Column('solarsystem_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost_index', sa.Numeric(precision=20, scale=19, decimal_return_scale=19), nullable=True),
    sa.ForeignKeyConstraint(['solarsystem_id'], ['solar_system.id'], ),
    sa.PrimaryKeyConstraint('solarsystem_id', 'activity', 'date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_index')
    ### end Alembic commands ###
