"""add groupID in item

Revision ID: 71707fb4716f
Revises: dfbab532195b
Create Date: 2018-07-20 14:32:43.181000

"""

# revision identifiers, used by Alembic.
revision = '71707fb4716f'
down_revision = 'dfbab532195b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('group_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'group_id')
    # ### end Alembic commands ###
