"""add validity state for tokenScopes

Revision ID: 86d4d399a174
Revises: 914830834002
Create Date: 2017-03-10 16:10:08.916000

"""

# revision identifiers, used by Alembic.
revision = '86d4d399a174'
down_revision = '914830834002'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_scope', sa.Column('request_try', sa.Integer(), nullable=True))
    op.add_column('token_scope', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_scope', 'valid')
    op.drop_column('token_scope', 'request_try')
    # ### end Alembic commands ###
