"""add validity state for tokenScopes

Revision ID: 86d4d399a174
Revises: 914830834002
Create Date: 2017-03-10 16:10:08.916000

"""

# revision identifiers, used by Alembic.
import sqlalchemy as sa

from alembic import op
from lazyblacksmith.models import TokenScope
from lazyblacksmith.models import db
revision = '86d4d399a174'
down_revision = '914830834002'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_scope',
                  sa.Column('request_try', sa.Integer(), nullable=False))
    op.add_column('token_scope',
                  sa.Column('valid', sa.Boolean(), nullable=False))

    TokenScope.query.update({'valid': True, 'request_try': 0})
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_scope', 'valid')
    op.drop_column('token_scope', 'request_try')
    # ### end Alembic commands ###
