"""industry index remove date

Revision ID: 88d46e8e73ef
Revises: 6543398f0773
Create Date: 2016-03-08 19:51:18.026000

"""

# revision identifiers, used by Alembic.
revision = '88d46e8e73ef'
down_revision = '6543398f0773'

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_index', 'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_index', sa.Column('date', mysql.DATETIME(), nullable=False))
    ### end Alembic commands ###
