"""add character to pref

Revision ID: 914830834002
Revises: 9c192a1cf2b2
Create Date: 2017-02-20 16:06:33.078969

"""

# revision identifiers, used by Alembic.
revision = '914830834002'
down_revision = '9c192a1cf2b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preference', sa.Column('invention_character_id', sa.BigInteger(), nullable=True))
    op.add_column('user_preference', sa.Column('prod_character_id', sa.BigInteger(), nullable=True))
    op.add_column('user_preference', sa.Column('research_character_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_preference', 'user', ['prod_character_id'], ['character_id'])
    op.create_foreign_key(None, 'user_preference', 'user', ['invention_character_id'], ['character_id'])
    op.create_foreign_key(None, 'user_preference', 'user', ['research_character_id'], ['character_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_preference', type_='foreignkey')
    op.drop_constraint(None, 'user_preference', type_='foreignkey')
    op.drop_constraint(None, 'user_preference', type_='foreignkey')
    op.drop_column('user_preference', 'research_character_id')
    op.drop_column('user_preference', 'prod_character_id')
    op.drop_column('user_preference', 'invention_character_id')
    # ### end Alembic commands ###
