"""add current_login_at in user to track login

Revision ID: 9c192a1cf2b2
Revises: 1ab760813798
Create Date: 2017-02-08 10:10:30.183117

"""

# revision identifiers, used by Alembic.
revision = '9c192a1cf2b2'
down_revision = '1ab760813798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_login_at')
    # ### end Alembic commands ###
