"""fix typo

Revision ID: a708fc036755
Revises: e2271bba31e1
Create Date: 2016-08-10 21:50:36.139000

"""

# revision identifiers, used by Alembic.
revision = 'a708fc036755'
down_revision = 'e2271bba31e1'

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_price', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('item_price', 'update_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_price', sa.Column('update_at', mysql.DATETIME(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('item_price', 'updated_at')
    ### end Alembic commands ###
