"""remove_refresh_token

Revision ID: ce1e397f5ac
Revises: 1f7133f7a45d
Create Date: 2015-08-03 22:15:10.649000

"""

# revision identifiers, used by Alembic.
revision = 'ce1e397f5ac'
down_revision = '1f7133f7a45d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eve_user', 'refresh_token_expires_on')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eve_user', sa.Column('refresh_token_expires_on', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
