"""add decryptor table

Revision ID: d7ae554d1766
Revises: 479a4b40f818
Create Date: 2016-08-26 09:56:14.301093

"""

# revision identifiers, used by Alembic.
revision = 'd7ae554d1766'
down_revision = '479a4b40f818'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decryptor',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('probability_multiplier', sa.Numeric(precision=4, scale=2, decimal_return_scale=2, asdecimal=False), nullable=True),
    sa.Column('material_modifier', sa.Integer(), nullable=True),
    sa.Column('time_modifier', sa.Integer(), nullable=True),
    sa.Column('run_modifier', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decryptor')
    ### end Alembic commands ###
