"""add base price to items

Revision ID: dfbab532195b
Revises: 864b4038799b
Create Date: 2018-07-18 15:45:21.079000

"""

# revision identifiers, used by Alembic.
revision = 'dfbab532195b'
down_revision = '864b4038799b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('base_cost', sa.Numeric(precision=17, scale=2, decimal_return_scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'base_cost')
    # ### end Alembic commands ###
