"""add update in price

Revision ID: e2271bba31e1
Revises: 1eb336920751
Create Date: 2016-08-09 10:41:23.365428

"""

# revision identifiers, used by Alembic.
revision = 'e2271bba31e1'
down_revision = '1eb336920751'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_price', sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_price', 'update_at')
    ### end Alembic commands ###
