"""add task status table

Revision ID: e41434540dca
Revises: 26103728d838
Create Date: 2017-01-04 11:52:58.028628

"""

# revision identifiers, used by Alembic.
revision = 'e41434540dca'
down_revision = '26103728d838'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('expire', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_status')
    # ### end Alembic commands ###
