"""add character skills

Revision ID: ef98dde149ee
Revises: 9d6c1ba6274d
Create Date: 2017-01-06 21:58:29

"""

# revision identifiers, used by Alembic.
revision = 'ef98dde149ee'
down_revision = '9d6c1ba6274d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['eve_user.character_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    # ### end Alembic commands ###
