"""add vooule to items

Revision ID: f47c65a1d309
Revises: fd9e5381922d
Create Date: 2019-01-18 10:39:25.643957

"""

# revision identifiers, used by Alembic.
revision = 'f47c65a1d309'
down_revision = 'fd9e5381922d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('volume', sa.Numeric(precision=16, scale=4, decimal_return_scale=4, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'volume')
    # ### end Alembic commands ###
