"""item_price item marketgroupid categoryid

Revision ID: f5518fbefd44
Revises: 2f83257f6912
Create Date: 2016-02-15 00:52:18.756000

"""

# revision identifiers, used by Alembic.
revision = 'f5518fbefd44'
down_revision = '2f83257f6912'

import sqlalchemy as sa

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_adjusted_price',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('price', sa.Numeric(precision=17, scale=2, decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_price',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=17, scale=2, decimal_return_scale=2), nullable=True),
    sa.Column('buy_price', sa.Numeric(precision=17, scale=2, decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.add_column(u'item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column(u'item', sa.Column('market_group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'item', 'market_group_id')
    op.drop_column(u'item', 'category_id')
    op.drop_table('item_price')
    op.drop_table('item_adjusted_price')
    ### end Alembic commands ###
