"""add token scope remove token from user

Revision ID: f637f29c715c
Revises: 1d7cccca46b3
Create Date: 2017-01-27 13:28:25.253365

"""

# revision identifiers, used by Alembic.
revision = 'f637f29c715c'
down_revision = '1d7cccca46b3'

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_scope',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token', sa.String(length=100), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.character_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scope')
    )
    op.drop_column(u'user', 'access_token')
    op.drop_column(u'user', 'access_token_expires')
    op.drop_column(u'user', 'refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('refresh_token', sa.String(length=100), nullable=True))
    op.add_column(u'user', sa.Column('access_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column(u'user', sa.Column('access_token', sa.String(length=100), nullable=True))
    op.drop_table('token_scope')
    # ### end Alembic commands ###
